### PR TITLE
MINOR: fixing some wording

### PR DESCRIPTION
**Pull request by spekulatius**
MINOR tweaks to the wording.

### CODE REVIEW

**Comment by tabuna** [comment]
Hi Peter, I'm grateful for the text correction

**Comment by spekulatius** [comment]
No worries. I'm playing around with Orchid a bit. I'll let you know if stumble across more stuff.

**Comment by spekulatius** [comment]
Let me know if you need any assistance with merging this @tabuna

**Comment by tabuna** [comment]
Oh no thank you, but I would be very glad to receive your feedback or suggestions about the package

**Comment by spekulatius** [comment]
Absolutely understandable :) I'll let you know as soon as I had more a play

**Pull request merged**
